services:

  mysql:
    image: mysql:8.0

    container_name: xyz-bank-mysql

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: Root@2026
      MYSQL_DATABASE: xyz_bank

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

  app:

    build: .

    container_name: xyz-bank-app

    ports:
      - "8081:8081"

    depends_on:
      - mysql

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/xyz_bank
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Root@2026

volumes:
  mysql-data: