apiVersion : v1
kind: Service   
metadata:
  name: xyz-bank-service
  namespace: xyz-bank     
spec:
  selector:
    app: xyz-bank
    type: NodePort

    ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081  
      nodePort:30081